apiVersion: v1
data:
  elastalert_config.yaml: |-
    rules_folder: /opt/rules
    run_every:
      minutes: 1
    buffer_time:
      minutes: 15
    es_host: elasticsearch
    es_port: 9200
    es_debug: true
    writeback_index: elastalert_status
    alert_time_limit:
      days: 2
kind: ConfigMap
metadata:
  name: elastalert
  namespace: elastalert
