apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: elastalert
  name: elastalert
  namespace: elastalert
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: elastalert
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elastalert
    spec:
      containers:
      - image: foxdalas/elastalert:latest
        imagePullPolicy: Always
        name: elastalert
        volumeMounts:
        - name: config-volume
          mountPath: /opt/config
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: config-volume
          configMap:
            name: elastalert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
